config/routes.rb
Rails.application.routes.draw do
  resources :cars
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "cars#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  validates :model, presence: true, length: {minimum:3, maximum:10}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :user_name, presence: true, length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true, uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy!

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:model, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def show
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end  

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User registered successfully."
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
    flash[:notice] = "User information updated succesfully"
    redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "User deleted succesfully"
    redirect_to users_path
  end
  
  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Model:</strong>
    <%= car.model %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= car.description %>
  </p>

</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :model, style: "display: block" %>
    <%= form.text_field :model %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cars | <%= link_to "View Users", users_path%></h1>

<div id="cars">
  <% @cars.each do |car| %>
    <%= render car %>
    <p>
      <%= link_to "Show this car", car %>
    </p>
  <% end %>
</div>

<%= link_to "New car", new_car_path %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div>
  <%= link_to "Edit this car", edit_car_path(@car) %> |
  <%= link_to "Back to cars", cars_path %>

  <%= button_to "Destroy this car", @car, method: :delete %>
</div>

app/views/layouts/_messages.html.erb
<%flash.each do |name, msg|%>
    <%=msg%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% if user.errors.any? %>
    <h2><%= pluralize(user.errors.count, "error") %> prohibited user from being saved:</h2>

    <ul>
    <% user.errors.each do |error| %>
        <li><%= error.full_message %></li>
    <% end %>
    </ul>
<% end %>

<%= form_with(model: user) do |f|%>
    <p><%=f.label :user_name%></p>
    <%=f.text_field :user_name%><br>
    <p><%=f.label :email%></p>
    <%=f.email_field :email%><br>
    <p><%=f.label :password%></p>
    <%=f.password_field :password%><br>
    <p><%=f.submit%></p>
<%end%>

app/views/users/edit.html.erb
<h1>Edit User information</h1>
<%=render 'form', user: @user%>
<%=link_to "Cancel", users_path%>

app/views/users/index.html.erb
<h1> Registered users </h1>

<table>
    <thead>
        <tr>
            <th>User name</th>
            <th>Email</th>
            <th colspan="3">action</th>
        </tr>
    </thead>

    <tbody>
        <%@users.each do |user|%>
            <tr>
                <td><%=user.user_name%></td>
                <td><%=user.email%></td>
                <td>
                    <%=link_to "view", user%>
                    <%=link_to "edit", edit_user_path(user)%>
                    <%=link_to "delete", user, data: { turbo_method: :delete, 
                    turbo_confirm: "Alert!: You are deleting user: #{user.user_name}, please confirm"}%>
                </td>
            </tr>
        <%end%>
    </tbody>
</table>
<br><strong><%=link_to "New user", new_user_path%></strong> 

app/views/users/new.html.erb
<h1>Register new user</h1>
<%=render 'form', user: @user%>
<%=link_to "cancel", users_path%>

app/views/users/show.html.erb
<h1>User details</h1>

<body>
    <ul>
        <li><%=@user.user_name%></li>
        <li><%=@user.email%></li>
    </ul>

    <%=link_to "new user", new_user_path%> |
    <%=link_to "edit user", edit_user_path(@user)%>
</body>